Repository Icinga/icingaweb2-module-businessprocess, pull requests merged in 2020-02, with the labels that each got.

#255 New CLI options and display name usage
  application/clicommands/ProcessCommand.php
  library/Businessprocess/BpNode.php
  library/Businessprocess/HostNode.php
  library/Businessprocess/Node.php
  library/Businessprocess/Renderer/TileRenderer/NodeTile.php
  library/Businessprocess/ServiceNode.php
  library/Businessprocess/State/MonitoringState.php
  test/php/library/Businessprocess/HostNodeTest.php
  test/php/library/Businessprocess/ServiceNodeTest.php
Labels: enhancement, ref/NC

#264 ProcessCommand: handle errors as UNKNOWN
  application/clicommands/ProcessCommand.php
Labels: bug

#262 Add animations for breadcrumbs on impact
  public/css/module.less
Labels: bug

#266 Fix references to unbound nodes
  library/Businessprocess/Node.php
Labels: bug

#268 Fix superfluous base target overrides
  library/Businessprocess/Renderer/TileRenderer.php
  library/Businessprocess/Renderer/TileRenderer/NodeTile.php
Labels: bug

#265 Fix URL param overrides upon rendering
  library/Businessprocess/Renderer/Renderer.php
  library/Businessprocess/Renderer/TileRenderer.php
  library/Businessprocess/Renderer/TreeRenderer.php
Labels: bug

#248 Make it possible to delete imported nodes
  library/Businessprocess/Renderer/TileRenderer/NodeTile.php
Labels: bug

#273 Fix PHP 7.4 compatibility
  library/Businessprocess/Node.php
  library/vendor/php-diff/lib/Diff/Renderer/Html/Array.php
Labels: enhancement
