Repository Icinga/icingaweb2-module-businessprocess, pull requests merged in 2022-03, with the labels that each got.

#305 Redesign state badge widget on tiles
  doc/02-Installation.md
  library/Businessprocess/BpNode.php
  library/Businessprocess/Renderer/Renderer.php
  library/Businessprocess/Renderer/TileRenderer/NodeTile.php
  module.info
  public/css/module.less
Labels: cla/signed

#320 Re-add php-diff library
  .github/workflows/php.yml
  doc/02-Installation.md
  library/Businessprocess/Storage/ConfigDiff.php
  library/vendor/php-diff/README
  library/vendor/php-diff/composer.json
  library/vendor/php-diff/example/a.txt
  library/vendor/php-diff/example/b.txt
  library/vendor/php-diff/example/example.php
  library/vendor/php-diff/example/styles.css
  library/vendor/php-diff/lib/Diff.php
  library/vendor/php-diff/lib/Diff/Renderer/Abstract.php
  library/vendor/php-diff/lib/Diff/Renderer/Html/Array.php
  library/vendor/php-diff/lib/Diff/Renderer/Html/Inline.php
  library/vendor/php-diff/lib/Diff/Renderer/Html/SideBySide.php
  library/vendor/php-diff/lib/Diff/Renderer/Text/Context.php
  library/vendor/php-diff/lib/Diff/Renderer/Text/Unified.php
  library/vendor/php-diff/lib/Diff/SequenceMatcher.php
  public/css/module.less
Labels: cla/signed

#322 Update docs
  README.md
  doc/screenshot/00_preview/0001_preview-tree-view.png
  doc/screenshot/00_preview/0002_preview_tile_view.png
  doc/screenshot/00_preview/0003_preview_businessprocesses_on_dashboard.png
  doc/screenshot/00_preview/0004_preview_tile_and_subtree.png
  doc/screenshot/00_preview/0005_preview-smaller-tile-view.png
  doc/screenshot/00_preview/0005_readme-preview.png
  doc/screenshot/00_preview/0006_preview-smaller-tree-view.png
  doc/screenshot/00_preview/0007_preview-smallerbusinessprocesses-on-dashboard.png
  doc/screenshot/13_web-components-tile-renderer/1301_tile-view.png
  doc/screenshot/13_web-components-tile-renderer/1302_tile-and-subtree.png
  doc/screenshot/14_web-components-tree-renderer/1401_tree-view.png
  doc/screenshot/16_dashboard/1603_businessprocesses_on_dashboard.png
  module.info
Labels: cla/signed

#323 Properly handle view compact requests
  library/Businessprocess/Web/Controller.php
Labels: bug, cla/signed

#288 Permissions: add form elements and documentation
  README.md
  application/forms/BpConfigForm.php
  doc/31-Permissions.md
Labels: enhancement, cla/signed

#321 Remove php-diff library
  .github/workflows/php.yml
  README.md
  doc/02-Installation.md
  library/Businessprocess/Storage/ConfigDiff.php
  library/vendor/php-diff/README
  library/vendor/php-diff/composer.json
  library/vendor/php-diff/example/a.txt
  library/vendor/php-diff/example/b.txt
  library/vendor/php-diff/example/example.php
  library/vendor/php-diff/example/styles.css
  library/vendor/php-diff/lib/Diff.php
  library/vendor/php-diff/lib/Diff/Renderer/Abstract.php
  library/vendor/php-diff/lib/Diff/Renderer/Html/Array.php
  library/vendor/php-diff/lib/Diff/Renderer/Html/Inline.php
  library/vendor/php-diff/lib/Diff/Renderer/Html/SideBySide.php
  library/vendor/php-diff/lib/Diff/Renderer/Text/Context.php
  library/vendor/php-diff/lib/Diff/Renderer/Text/Unified.php
  library/vendor/php-diff/lib/Diff/SequenceMatcher.php
  public/css/module.less
Labels: cla/signed
