Repository Icinga/icingaweb2-module-businessprocess, pull requests merged in 2023-10, with the labels that each got.

#414 IcingaDbState: Ensure compatibility with Icinga DB Web 1.0 and 1.1
  library/Businessprocess/State/IcingaDbState.php
Labels: bug, cla/signed

#416 Backport #337 to support/2.4
  library/Businessprocess/BpNode.php
Labels: bug, cla/signed

#417 Backport #350 to support/2.4
  library/Businessprocess/Common/EnumList.php
Labels: bug, cla/signed

#418 Backport #346 to support/2.4
  application/controllers/HostController.php
  application/controllers/ServiceController.php
  library/Businessprocess/State/IcingaDbState.php
Labels: bug, cla/signed

#419 Backport #393 to support/2.4
  library/Businessprocess/State/IcingaDbState.php
Labels: bug, cla/signed

#420 Release version 2.4.1
  module.info
Labels: cla/signed

#423 PHPStan: Update baseline
  phpstan-baseline.neon
Labels: cla/signed

#424 Update default branch references
  .github/workflows/L10n-update.yml
  .github/workflows/php.yml
  README.md
Labels: cla/signed

#422 doc: Adjust accordingly to our new packaging docs
  doc/01-About.md
  doc/02-Installation.md
  doc/02-Installation.md.d/From-Source.md
  doc/03-Getting-Started.md
  doc/04-Create-your-first-process-node.md
  doc/05-Importing-Processes.md
  doc/06-Customize-Node-Order.md
  doc/09-Operators.md
  doc/12-Web-Components-Breadcrumb.md
  doc/13-Web-Components-Tile-Renderer.md
  doc/14-Web-Components-Tree-Renderer.md
  doc/16-Add-To-Dashboard.md
  doc/21-Store-Config.md
  doc/22-Upload-Config.md
  doc/31-Permissions.md
  doc/81-History.md
Labels: enhancement, cla/signed

#425 Release v2.5.0
  README.md
  doc/02-Installation.md.d/From-Source.md
  module.info
  packaging/debian/README.1st
  packaging/debian/changelog
  packaging/debian/compat
  packaging/debian/control
  packaging/debian/docs
  packaging/debian/install
  packaging/debian/rules
  packaging/debian/source/format
Labels: cla/signed
