Repository Icinga/icingaweb2-module-businessprocess, pull requests merged in 2023-08, with the labels that each got.

#358 DeleteNodeForm: Remove stateoverrides of node by removing node
  library/Businessprocess/Modification/NodeRemoveAction.php
Labels: bug, cla/signed

#355 Clean orphaned (missing) nodes
  application/clicommands/CleanupCommand.php
  application/controllers/ProcessController.php
  application/forms/CleanupNodeForm.php
Labels: enhancement, cla/signed

#375 Do not break overview page if existing `business pocesses` throw exceptions
  application/controllers/NodeController.php
  application/forms/AddNodeForm.php
  library/Businessprocess/Web/Component/BpDashboardTile.php
  library/Businessprocess/Web/Component/Dashboard.php
  library/Businessprocess/Web/Component/DashboardAction.php
  public/css/module.less
Labels: bug, cla/signed

#361 Add custom message for form's regex validation
  application/forms/BpConfigForm.php
  application/forms/BpUploadForm.php
Labels: cla/signed

#348 Show Ack/Downtime icons in the node tiles for the handled nodes
  library/Businessprocess/Renderer/TileRenderer/NodeTile.php
  public/css/module.less
Labels: enhancement, cla/signed

#352 Show `Ack` icon in tree view for nodes with both downtime and acknowledgement
  library/Businessprocess/Renderer/TreeRenderer.php
  public/css/module.less
Labels: cla/signed

#384 Support custom ordering of nodes
  application/controllers/ProcessController.php
  application/forms/AddNodeForm.php
  application/forms/BpConfigForm.php
  application/forms/BpUploadForm.php
  application/forms/DeleteNodeForm.php
  application/forms/EditNodeForm.php
  application/forms/MoveNodeForm.php
  application/forms/ProcessForm.php
  application/forms/SimulationForm.php
  library/Businessprocess/BpConfig.php
  library/Businessprocess/BpNode.php
  library/Businessprocess/Common/Sort.php
  library/Businessprocess/Modification/NodeApplyManualOrderAction.php
  library/Businessprocess/Modification/NodeCopyAction.php
  library/Businessprocess/Modification/NodeMoveAction.php
  library/Businessprocess/Renderer/Renderer.php
  library/Businessprocess/Renderer/TileRenderer.php
  library/Businessprocess/Renderer/TreeRenderer.php
  library/Businessprocess/Storage/LegacyStorage.php
  library/Businessprocess/Web/Controller.php
  library/Businessprocess/Web/Form/BpConfigBaseForm.php
  public/css/module.less
  public/js/module.js
Labels: enhancement, ref/NC, cla/signed

#388 Escape semicolons in node names
  application/forms/AddNodeForm.php
  application/forms/EditNodeForm.php
  library/Businessprocess/BpConfig.php
  library/Businessprocess/BpNode.php
  library/Businessprocess/Common/EnumList.php
  library/Businessprocess/HostNode.php
  library/Businessprocess/ImportedNode.php
  library/Businessprocess/Modification/NodeAddChildrenAction.php
  library/Businessprocess/ProvidedHook/Icingadb/HostActions.php
  library/Businessprocess/ProvidedHook/Icingadb/ServiceActions.php
  library/Businessprocess/ProvidedHook/Monitoring/HostActions.php
  library/Businessprocess/ProvidedHook/Monitoring/ServiceActions.php
  library/Businessprocess/ServiceNode.php
  library/Businessprocess/State/IcingaDbState.php
  library/Businessprocess/State/MonitoringState.php
  library/Businessprocess/Storage/LegacyConfigParser.php
  test/config/modules/businessprocess/processes/also-with-semicolons.conf
  test/config/modules/businessprocess/processes/with-semicolons.conf
  test/php/library/Businessprocess/BpConfigTest.php
  test/php/library/Businessprocess/Storage/LegacyStorageTest.php
Labels: bug, cla/signed

#383 Use `ipl\Web\Widget\Icon` class everywhere
  application/controllers/ProcessController.php
  library/Businessprocess/BpNode.php
  library/Businessprocess/HostNode.php
  library/Businessprocess/Node.php
  library/Businessprocess/Renderer/Breadcrumb.php
  library/Businessprocess/Renderer/TileRenderer/NodeTile.php
  library/Businessprocess/Renderer/TreeRenderer.php
  library/Businessprocess/ServiceNode.php
  library/Businessprocess/Web/Component/RenderedProcessActionBar.php
  public/css/module.less
Labels: cla/signed

#393 IcingaDbState: Optimize queries
  library/Businessprocess/State/IcingaDbState.php
Labels: bug, cla/signed

#395 (Cleanup/Move)NodeForm extend new BpConfigBaseForm
  application/forms/CleanupNodeForm.php
  application/forms/MoveNodeForm.php
Labels: cla/signed

#396 IcingaDbState: Apply state data from redis
  library/Businessprocess/State/IcingaDbState.php
Labels: bug, cla/signed

#387 Add auto completion
  application/controllers/ProcessController.php
  application/controllers/SuggestionsController.php
  application/forms/AddNodeForm.php
  application/forms/EditNodeForm.php
  library/Businessprocess/BpNode.php
  library/Businessprocess/Common/EnumList.php
  library/Businessprocess/Monitoring/Backend/Ido/Query/CustomVarJoinTemplateOverride.php
  library/Businessprocess/Monitoring/Backend/Ido/Query/HostStatusQuery.php
  library/Businessprocess/Monitoring/Backend/Ido/Query/ServiceStatusQuery.php
  library/Businessprocess/Monitoring/DataView/HostStatus.php
  library/Businessprocess/Monitoring/DataView/ServiceStatus.php
  library/Businessprocess/ServiceNode.php
  library/Businessprocess/Web/Form/Element/IplStateOverrides.php
  library/Businessprocess/Web/Form/Element/StateOverrides.php
  library/Businessprocess/Web/Form/Validator/HostServiceTermValidator.php
  library/Businessprocess/Web/Form/Validator/NoDuplicateChildrenValidator.php
  public/css/module.less
  test/php/library/Businessprocess/ServiceNodeTest.php
Labels: enhancement, cla/signed

#397 BpNode::getMissingChildren(): Use child name if alias not given
  library/Businessprocess/BpNode.php
Labels: bug, cla/signed

#378 workflows: Add Phpstan
  .github/workflows/php.yml
  application/clicommands/ProcessCommand.php
  application/controllers/HostController.php
  application/controllers/ProcessController.php
  application/controllers/ServiceController.php
  application/forms/AddNodeForm.php
  application/forms/BpUploadForm.php
  application/forms/DeleteNodeForm.php
  application/forms/MoveNodeForm.php
  application/forms/ProcessForm.php
  application/forms/SimulationForm.php
  application/views/helpers/FormStateOverrides.php
  library/Businessprocess/BpConfig.php
  library/Businessprocess/BpNode.php
  library/Businessprocess/Common/Sort.php
  library/Businessprocess/Form.php
  library/Businessprocess/Modification/NodeAction.php
  library/Businessprocess/Modification/NodeRemoveAction.php
  library/Businessprocess/Modification/ProcessChanges.php
  library/Businessprocess/Node.php
  library/Businessprocess/ProvidedHook/Icingadb/ServiceDetailExtension.php
  library/Businessprocess/ProvidedHook/Monitoring/DetailviewExtension.php
  library/Businessprocess/Renderer/Breadcrumb.php
  library/Businessprocess/Renderer/Renderer.php
  library/Businessprocess/Renderer/TileRenderer/NodeTile.php
  library/Businessprocess/Storage/LegacyConfigParser.php
  library/Businessprocess/Storage/LegacyConfigRenderer.php
  library/Businessprocess/Test/BaseTestCase.php
  library/Businessprocess/Web/Component/RenderedProcessActionBar.php
  library/Businessprocess/Web/Controller.php
  library/Businessprocess/Web/Form/FormLoader.php
  library/Businessprocess/Web/Form/QuickBaseForm.php
  library/Businessprocess/Web/Form/QuickForm.php
  library/Businessprocess/Web/Form/Validator/HostServiceTermValidator.php
  library/Businessprocess/Web/Navigation/Renderer/ProcessProblemsBadge.php
  library/Businessprocess/Web/Url.php
  phpstan-baseline.neon
  phpstan.neon
Labels: cla/signed
