Repository Icinga/icingaweb2-module-businessprocess, pull requests merged in 2023-07, with the labels that each got.

#380 LegacyConfigParser: Ignore empty lines in `parseHeaderLine()`
  library/Businessprocess/Storage/LegacyConfigParser.php
Labels: bug, cla/signed

#376 MetaData: Introduce new header option `HideId`
  library/Businessprocess/Web/Component/Dashboard.php
Labels: enhancement, cla/signed

#381 Drop external_info and extra_info flag support
  library/Businessprocess/BpNode.php
  library/Businessprocess/Storage/LegacyConfigParser.php
Labels: cla/signed

#382 Show node id in edit mode
  application/forms/ProcessForm.php
Labels: enhancement, cla/signed

#360 Display node name if alias for monitoring node is missing
  application/forms/DeleteNodeForm.php
  application/forms/EditNodeForm.php
  application/forms/SimulationForm.php
  library/Businessprocess/MonitoredNode.php
  library/Businessprocess/Renderer/TileRenderer/NodeTile.php
  library/Businessprocess/ServiceNode.php
Labels: bug, cla/signed

#336 TreeRenderer: Use Icinga Web's collapsible implementation now
  library/Businessprocess/Renderer/Renderer.php
  library/Businessprocess/Renderer/TreeRenderer.php
  public/css/module.less
  public/js/module.js
Labels: enhancement, cla/signed
