Repository Icinga/icingaweb2-module-businessprocess, pull requests merged in 2024-04, with the labels that each got.

#443 Fix: Switching to the icingadb backend and searching host/service node in add/edit form throws an error
  library/Businessprocess/Web/Form/Validator/HostServiceTermValidator.php
  phpstan-baseline-standard.neon
Labels: bug, cla/signed

#448 phpstan: Separate workflow
  .github/workflows/php.yml
  .github/workflows/phpstan.yml
Labels: enhancement, cla/signed

#445 ProcessCommand: Fix false positive condition for `ServiceNode`
  application/clicommands/ProcessCommand.php
Labels: bug, cla/signed

#426 Drop empty files
  doc/screenshot/00_preview/0003_preview_businessprocesses_on_dashboard.png
  test/config/authentication.ini
  test/config/config.ini
Labels: cla/signed

#441 module.less: Fix align of action-bar and sort control
  public/css/module.less
Labels: bug, cla/signed

#446 phpstan: Fix generic type errors
  library/Businessprocess/Common/Sort.php
  library/Businessprocess/Storage/Storage.php
  phpstan-baseline-standard.neon
Labels: enhancement, cla/signed

#444 Correct notification messages and add missing translations
  application/forms/BpConfigForm.php
  application/forms/BpUploadForm.php
  application/forms/CleanupNodeForm.php
  application/forms/DeleteNodeForm.php
  application/forms/MoveNodeForm.php
  application/forms/ProcessForm.php
  application/forms/SimulationForm.php
  library/Businessprocess/Web/Form/QuickBaseForm.php
  phpstan-baseline-standard.neon
  public/js/module.js
Labels: bug, cla/signed

#438 Fix that handled nodes are not handled
  library/Businessprocess/BpNode.php
  library/Businessprocess/Web/Component/BpDashboardTile.php
Labels: bug, ref/IP, cla/signed

#433 Fix indistinguishable suggestions for nodes
  application/controllers/SuggestionsController.php
  application/forms/AddNodeForm.php
  library/Businessprocess/Node.php
Labels: bug, cla/signed

#449 Release v2.5.1
  module.info
Labels: cla/signed
